version: '3'

services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    environment:
       - LDAP_LOG_LEVEL=32768
       - LDAP_ORGANISATION=example.org
       - LDAP_DOMAIN=example.org
       - LDAP_BASE_DN=
       - LDAP_ADMIN_PASSWORD=XXXXXXXXXXXXXX
       - LDAP_CONFIG_PASSWORD=XXXXXXXXXXXXXX
       - LDAP_READONLY_USER=true
       - LDAP_READONLY_USER_USERNAME=binddn
       - LDAP_READONLY_USER_PASSWORD=XXXXXXXXXXXXXX
       - LDAP_RFC2307BIS_SCHEMA=false
       - LDAP_BACKEND=mdb
       - LDAP_TLS=true
       - LDAP_TLS_CRT_FILENAME=ldap.crt
       - LDAP_TLS_KEY_FILENAME=ldap.key
       - LDAP_TLS_CA_CRT_FILENAME=ca.crt
       - LDAP_TLS_ENFORCE=false
       - LDAP_TLS_CIPHER_SUITE=SECURE256:-VERS-SSL3.0
       - LDAP_TLS_PROTOCOL_MIN=3.1
       - LDAP_TLS_VERIFY_CLIENT=allow
       - LDAP_REPLICATION=false
       - KEEP_EXISTING_CONFIG=false
       - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
       - LDAP_SSL_HELPER_PREFIX=ldap
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - ./certs_ldap:/container/service/slapd/assets/certs:rw
    expose:
      - 389
      - 636
    ports:
      - 0.0.0.0:389:389/tcp
      - 0.0.0.0:389:389/udp
      - 0.0.0.0:636:636/tcp
      - 0.0.0.0:636:636/udp
      - 0.0.0.0:3268:3268/tcp
      - 0.0.0.0:3268:3268/udp
      - 0.0.0.0:3269:3269/tcp
      - 0.0.0.0:3269:3269/udp
    domainname: openldap
    hostname: openldap
    restart: unless-stopped
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    expose:
      - 443
    ports:
      - 0.0.0.0:443:443
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=true
    volumes:
      - ./certs_web:/container/service/phpldapadmin/assets/apache2/certs:rw
      - ./certs_web:/container/service/ldap-client/assets/certs:rw
    depends_on:
      - openldap
    domainname: phpldapadmin
    hostname: phpldapadmin
    restart: unless-stopped
